package sample;
import com.sun.deploy.xml.XMLable;
import javafx.application.Application;
import javafx.scene.layout.*;
import javafx.stage.Modality;
import javafx.geometry.Pos;
import javafx.geometry.Insets;
import javafx.scene.control.Label;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.control.TextArea;
import javafx.scene.control.ComboBox;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.scene.text.Font;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.text.*;
import javafx.scene.text.FontWeight;
import javafx.stage.Stage;
import javafx.scene.control.Button;
import javafx.scene.Scene;
import javafx.scene.shape.Line;
import javafx.scene.control.RadioButton;
import javafx.scene.control.ToggleGroup;

import java.util.ArrayList;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.stage.Modality;
import javafx.stage.Stage;
public class restartBox {
    public void display(String title , String message){
        Stage window = new Stage();
        window.setTitle(title);
        //modality要使用Modality.APPLICATION_MODEL
        window.initModality(Modality.APPLICATION_MODAL);
        window.setMinWidth(300);
        window.setMinHeight(150);
        HBox hBox = new HBox(16);
        hBox.setAlignment(Pos.CENTER);
        Button button = new Button("Yes");
        Button button1 = new Button("No");
        button1.setOnAction(e -> window.close());
        button.setOnAction(event -> {
            dice.count = 0;
            Yellow.YellowPiece1L = -2;
            Yellow.YellowPiece2L = -2;
            Yellow.YellowPiece3L = -2;
            Yellow.YellowPiece4L = -2;
            Yellow.YellowPiece12L = -2;
            Yellow.YellowPiece13L = -2;
            Yellow.YellowPiece14L = -2;
            Yellow.YellowPiece23L = -2;
            Yellow.YellowPiece24L = -2;
            Yellow.YellowPiece34L = -2;
            Yellow.YellowPiece123L = -2;
            Yellow.YellowPiece124L = -2;
            Yellow.YellowPiece234L = -2;
            Yellow.YellowPiece134L = -2;
            Yellow.YellowPiece1234L = -2;
            Yellow.YellowPieceIV1.setLayoutX(425);
            Yellow. YellowPieceIV1.setLayoutY(73);
            Yellow.YellowPieceIV1.setVisible(true);
            Yellow.YellowPieceIV2.setVisible(true);
            Yellow.YellowPieceIV3.setVisible(true);
            Yellow.YellowPieceIV4.setVisible(true);
            Yellow.YellowPieceIV12.setVisible(false);
            Yellow.YellowPieceIV13.setVisible(false);
            Yellow.YellowPieceIV14.setVisible(false);
            Yellow.YellowPieceIV23.setVisible(false);
            Yellow.YellowPieceIV24.setVisible(false);
            Yellow.YellowPieceIV34.setVisible(false);
            Yellow.YellowPieceIV123.setVisible(false);
            Yellow.YellowPieceIV124.setVisible(false);
            Yellow.YellowPieceIV134.setVisible(false);
            Yellow.YellowPieceIV234.setVisible(false);
            Yellow.YellowPieceIV1234.setVisible(false);
            Yellow.YellowPieceIV3.setLayoutX(476);
            Yellow.YellowPieceIV3.setLayoutY(22);
            Yellow.YellowPieceIV2.setLayoutX(424);
            Yellow.YellowPieceIV2.setLayoutY(22);
            Yellow.YellowPieceIV4.setLayoutX(477);
            Yellow.YellowPieceIV4.setLayoutY(72);
            Yellow.WinIV2.setVisible(false);
            Yellow.WinIV3.setVisible(false);
            Yellow.WinIV1.setVisible(false);
            Yellow.WinIV4.setVisible(false);
            Red.RedPieceIV1.setLayoutX(75);
            Red.RedPieceIV1.setLayoutY(74);
            Red.RedPieceIV3.setLayoutX(21);
            Red.RedPieceIV3.setLayoutY(74);
            Red.RedPieceIV2.setLayoutX(23);
            Red.RedPieceIV2.setLayoutY(21);
            Red.RedPieceIV4.setLayoutX(75);
            Red.RedPieceIV4.setLayoutY(22);
            Red.RedPieceIV1.setRotate(90);
            Red.RedPieceIV2.setRotate(90);
            Red.RedPieceIV3.setRotate(90);
            Red.RedPieceIV4.setRotate(90);
            Red.RedPieceIV12.setVisible(false);
            Red.RedPieceIV13.setVisible(false);
            Red.RedPieceIV14.setVisible(false);
            Red.RedPieceIV23.setVisible(false);
            Red.RedPieceIV24.setVisible(false);
            Red.RedPieceIV34.setVisible(false);
            Red.RedPieceIV123.setVisible(false);
            Red.RedPieceIV124.setVisible(false);
            Red.RedPieceIV134.setVisible(false);
            Red.RedPieceIV234.setVisible(false);
            Red.RedPieceIV1234.setVisible(false);
            Red.WinIV2.setVisible(false);
            Red.WinIV3.setVisible(false);
            Red.WinIV1.setVisible(false);
            Red.WinIV4.setVisible(false);
            Green.GreenPieceIV1.setLayoutX(75);
            Green.GreenPieceIV1.setLayoutY(478);
            Green.GreenPieceIV3.setLayoutX(75);
            Green.GreenPieceIV3.setLayoutY( 426);
            Green.GreenPieceIV2.setLayoutX(23);
            Green.GreenPieceIV2.setLayoutY(426);
            Green.GreenPieceIV4.setLayoutX(20);
            Green.GreenPieceIV4.setLayoutY( 478);
            Green.GreenPieceIV1.setRotate(180);
            Green.GreenPieceIV2.setRotate(180);
            Green.GreenPieceIV3.setRotate(180);
            Green.GreenPieceIV4.setRotate(180);
            Blue.BluePieceIV1.setLayoutX(426);
            Blue.BluePieceIV1.setLayoutY(426);
            Blue.BluePieceIV3.setLayoutX(426);
            Blue.BluePieceIV3.setLayoutY(478);
            Blue.BluePieceIV2.setLayoutX(478);
            Blue.BluePieceIV2.setLayoutY(479);
            Blue.BluePieceIV4.setLayoutX(479);
            Blue.BluePieceIV4.setLayoutY(426);
            Blue.BluePieceIV1.setRotate(0);
            Blue.BluePieceIV2.setRotate(0);
            Blue.BluePieceIV3.setRotate(0);
            Blue.BluePieceIV4.setRotate(0);
            Red.RedPiece1L = -2;
            Red.RedPiece2L = -2;
            Red.RedPiece3L = -2;
            Red.RedPiece4L = -2;
            Red.RedPiece12L = -2;
            Red.RedPiece13L = -2;
            Red.RedPiece14L = -2;
            Red.RedPiece23L = -2;
            Red.RedPiece24L = -2;
            Red.RedPiece34L = -2;
            Red.RedPiece123L = -2;
            Red.RedPiece124L = -2;
            Red.RedPiece234L = -2;
            Red.RedPiece134L = -2;
            Red.RedPiece1234L = -2;
            Red.WinIV2.setVisible(false);
            Red.WinIV3.setVisible(false);
            Red.WinIV1.setVisible(false);
            Red.WinIV4.setVisible(false);
            Blue.BluePiece1L = -2;
            Blue.BluePiece2L = -2;
            Blue.BluePiece3L = -2;
            Blue.BluePiece4L = -2;
            Blue.BluePiece12L = -2;
            Blue.BluePiece13L = -2;
            Blue.BluePiece14L = -2;
            Blue.BluePiece23L = -2;
            Blue.BluePiece24L = -2;
            Blue.BluePiece34L = -2;
            Blue.BluePiece123L = -2;
            Blue.BluePiece124L = -2;
            Blue.BluePiece234L = -2;
            Blue.BluePiece134L = -2;
            Blue.BluePiece1234L = -2;
            Blue.BluePieceIV12.setVisible(false);
            Blue.BluePieceIV13.setVisible(false);
            Blue.BluePieceIV14.setVisible(false);
            Blue.BluePieceIV23.setVisible(false);
            Blue.BluePieceIV24.setVisible(false);
            Blue.BluePieceIV34.setVisible(false);
            Blue.BluePieceIV123.setVisible(false);
            Blue.BluePieceIV124.setVisible(false);
            Blue.BluePieceIV134.setVisible(false);
            Blue.BluePieceIV234.setVisible(false);
            Blue.BluePieceIV1234.setVisible(false);
            Blue.WinIV2.setVisible(false);
            Blue.WinIV3.setVisible(false);
            Blue.WinIV1.setVisible(false);
            Blue.WinIV4.setVisible(false);
            Green.GreenPiece1L = -2;
            Green.GreenPiece2L = -2;
            Green.GreenPiece3L = -2;
            Green.GreenPiece4L = -2;
            Green.GreenPiece12L = -2;
            Green.GreenPiece13L = -2;
            Green.GreenPiece14L = -2;
            Green.GreenPiece23L = -2;
            Green.GreenPiece24L = -2;
            Green.GreenPiece34L = -2;
            Green.GreenPiece123L = -2;
            Green.GreenPiece124L = -2;
            Green.GreenPiece234L = -2;
            Green.GreenPiece134L = -2;
            Green.GreenPiece1234L = -2;
            Green.GreenPieceIV12.setVisible(false);
            Green.GreenPieceIV13.setVisible(false);
            Green.GreenPieceIV14.setVisible(false);
            Green.GreenPieceIV23.setVisible(false);
            Green.GreenPieceIV24.setVisible(false);
            Green.GreenPieceIV34.setVisible(false);
            Green.GreenPieceIV123.setVisible(false);
            Green.GreenPieceIV124.setVisible(false);
            Green.GreenPieceIV134.setVisible(false);
            Green.GreenPieceIV234.setVisible(false);
            Green.GreenPieceIV1234.setVisible(false);
            Green.WinIV2.setVisible(false);
            Green.WinIV3.setVisible(false);
            Green.WinIV1.setVisible(false);
            Green.WinIV4.setVisible(false);
            basepane.i = 2;
            basepane.yellowCount = 0;
            basepane.RedCount = 0;
            basepane.greenCount = 0;
            basepane.blueCount = 0;
            basepane.yellowFlagOpen = false;
            basepane.RedFlagOpen = false;
            basepane.greenFlagOpen = false;
            basepane.blueFlagOpen = false;
             basepane.Exception = 0;
            basepane.Exception2 = 0;
            basepane.diceNumber1 = 0;
            basepane.diceNumber2 = 0;
            basepane.num1 = 0;
            basepane.pace1 = 0;
            basepane.YellowFlag = false;
            basepane.RedFlag = false;
            basepane.BlueFlag = false;
            basepane.GreenFlag = false;
            Yellow. YellowFlag = false;
            dice.PlayerCount = 0;
            Yellow. y1 = 0;
            Yellow. y2 = 0;
            Yellow.  y3 = 0;
            Yellow.  y4 = 0;
            Yellow.y12 = 0;
            Yellow.y13 = 0;
            Yellow.y14 = 0;
            Yellow.y23 = 0;
            Yellow.y24= 0;
            Yellow.y34 = 0;
            Yellow.y123 = 0;
            Yellow.y124 = 0;
            Yellow.y134 = 0;
            Yellow.y234 = 0;
            Yellow.y1234 = 0;
            Yellow.  YellowNumber1 = 0;
            Yellow.  YellowNumber2 = 0;

            Red.  RedNumber1 = 0;
            Red. RedNumber2 = 0;
            Red.r1 = 0;
            Red.r2 = 0;
            Red.r3 = 0;
            Red.r4 = 0;
            Red.r12 = 0;
            Red.r13 = 0;
            Red.r14 = 0;
            Red.r23 = 0;
            Red.r24= 0;
            Red.r34 = 0;
            Red.r123 = 0;
            Red.r124 = 0;
            Red.r134 = 0;
            Red.r234 = 0;
            Red.r1234 = 0;
            Blue.b1 = 0;
            Blue.b2 = 0;
            Blue.b3 = 0;
            Blue.b4 = 0;
            Blue.b1 = 0;
            Blue.b2 = 0;
            Blue.b3 = 0;
            Blue.b4 = 0;
            Blue.b12 = 0;
            Blue.b13 = 0;
            Blue.b14 = 0;
            Blue.b23 = 0;
            Blue.b24= 0;
            Blue.b34 = 0;
            Blue.b123 = 0;
            Blue.b124 = 0;
            Blue.b134 = 0;
            Blue.b234 = 0;
            Blue.b1234 = 0;
            Green.GreenNumber1 = 0;
            Green. GreenNumber2 = 0;
            Green.g1 = 0;
            Green.g2 = 0;
            Green.g3 = 0;
            Green.g4 = 0;
            Green.g12 = 0;
            Green.g13 = 0;
            Green.g14 = 0;
            Green.g23 = 0;
            Green.g24= 0;
            Green.g34 = 0;
            Green.g123 = 0;
            Green.g124 = 0;
            Green.g134 = 0;
            Green.g234 = 0;
            Green.g1234 = 0;
            Blue. BlueNumber1 = 0;
            Blue. BlueNumber2 = 0;
            window.close();
        });
        Label label = new Label(message);
        hBox.getChildren().addAll(button,button1);
        VBox layout = new VBox(10);
        Image Save = new Image("SaveAlert.jpg");
        ImageView SaveIV = new ImageView(Save);
        SaveIV.setFitWidth(300);
        SaveIV.setFitHeight(150);
        layout.getChildren().add(SaveIV);
        layout.getChildren().addAll(label , hBox);
        layout.setAlignment(Pos.CENTER);

        Scene scene = new Scene(layout);
        window.setScene(scene);
        //使用showAndWait()先处理这个窗口，而如果不处理，main中的那个窗口不能响应
        window.showAndWait();
    }
}

